### PR TITLE
fix: form-level error reporting

### PR DESCRIPTION
**Pull request by nhedger**
This PR fixes an issue where form-level errors were set to the node's name when `formLevelErrorName` was left unspecified.

Specifying `formLevelErrorName` will now correctly render a form-level error if an error with the key specified by `formLevelErrorName` exists in the response payload. Also, leaving `formLevelErrorName` unspecified will ensure no form-level errors are displayed. 

FYI @fenilli

### CODE REVIEW

**Comment by fenilli** [comment]
One question I have tho, this was a feature I implemented out of the specs, but not sure how useful it is, as you're using it do you think it is a useful feature?

**Review by fenilli — CHANGES_REQUESTED** [review]
The reason for this feature was to set a global error message by the form name or another if specified, meaning it should by default be the name of the form, just was not meant to set the name of the field as the error but the global error itself.

Something like if you have a global error in laravel, you can just pass the name of the form field in the errors field and it would display there.

`node.setErrors(hasGlobalError ? formErrorMessage : [], errors)` should be this.

**Comment by nhedger** [comment]
> One question I have tho, this was a feature I implemented out of the specs, but not sure how useful it is, as you're using it do you think it is a useful feature?

I never use form-level errors, but I can see how someone might want to show one. When using Form Requests with Laravel, you usually attach errors only to the fields though.

**Comment by nhedger** [comment]
> The reason for this feature was to set a global error message by the form name or another if specified, meaning it should by default be the name of the form, just was not meant to set the name of the field as the error but the global error itself.
> 
> Something like if you have a global error in laravel, you can just pass the name of the form field in the errors field and it would display there.
> 
> `node.setErrors(hasGlobalError ? formErrorMessage : [], errors)` should be this.

Not sure I'm following.

My understanding was that by setting `formLevelErrorName`, you're essentially telling the `useForm` helper to hoist one of the field validation errors to the form level.

For example, say you have a login form, and submitting the form with invalid credentials would return the following error bag:

```json
{
  "email": "Invalid credentials"
}
```

You would set `formLevelErrorName` to `email` to render `Invalid credentials` at the form level instead of under the `email` input.

**Comment by fenilli** [comment]
That was not the reason but it could be too, but I would say for this its better to use other ways directly into the FormKit.

The thing I meant is is there an error like "The user was not created, call your IT". It is a global error.

```js
{
  userForm: 'The user was not created, call your IT',
}

<FormKit type="form" name="userForm">
</FormKit>
```

**Comment by nhedger** [comment]
I believe this should do it.

**Comment by fenilli** [comment]
This looks good I will work on it to publish a new version.

**Review by fenilli — APPROVED** [review]
Looks good to me.

**Comment by nhedger** [comment]
Thanks !

**Comment by fenilli** [comment]
This will be fixed after publishing `0.1.6`.

**Comment by nhedger** [comment]
Hey @fenilli, not meaning to press, but are you planning to release 0.1.6 soon-ish? No biggie if you don't have time, I can definitely fork in the meantime.

**Comment by fenilli** [comment]
@justin-schroeder did you publish to npm?

**Pull request merged**
